config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'concerts/', to: 'concerts#index', as: 'concerts'

  get 'tickets/', to: 'tickets#index', as: 'tickets'

  get 'vendors/', to: 'vendors#index', as: 'vendors'

  get 'contestants/', to: 'contestants#index', as: 'contestants'
  get 'contestants/register', to: 'contestants#register', as: 'registration'
  post 'contestants/register', to: 'users#create'

  get 'about/', to: 'about#index', as: 'about'

  get 'event/', to: 'event#index', as: 'event'

  get 'get_involved/', to: 'get_involved#index', as: 'getinvolved'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
  end
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  def index
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  end
end

app/controllers/get_involved_controller.rb
class GetInvolvedController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :user_type, :address, :city, :zip)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/get_involved_helper.rb
module GetInvolvedHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/about/index.html.erb
<div class='row'>
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <h1 class="d-block w-100 margin-0" alt="ABOUT TBFC">ABOUT</h1>
      </div>
    </div>
  </div>
</div>

<hr></hr>

<div class="row">
  <h2>History</h2>
  <p>It actually began in Topanga Canyon, California, thus the name, in Southern California's Santa Monica Mountains, home to writers, artists and lots of music people, a remote pocket of sylvan beauty just east of Malibu and the Pacific Ocean. A few old time and Bluegrass music-loving diehards are still around who can remember the first "Banjo Pickers and Open Fiddling Contest" created by Margot Slocum and Peg Benepe as a fund raiser for the Santa Monica Friends Meeting House.

  <p>It was 1961 and the music-only event attracted 26 Five-String Banjo Pickers, Five Fiddlers, Four Judges and more then 500 eager fans to Ian Thiermann's place amid the native oaks known as "Friendly Acres." It was such great fun, everyone agreed the contest was a wonderful idea and the contest would have to be put on again and again.
  </p>
</div>

app/views/application/index.html.erb
<div class="row">
  <div class="col-12 tagline">
    <i>Since 1961, Southern California's Favorite Bluegrass, Old-Time and Folk Music Festival</i>
  </div>
</div>

<div class="row">
  <div id="carouselExampleSlidesOnly" class="carousel slide col-12" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'application/carousel_image1.jpg', class: 'd-block w-100' %>
        <div class="carousel-caption">
          <h3>NEXT EVENT:<br>May 20th, 2018</h3>
          <h6 class="d-none d-md-block">Save the date!</h6>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'application/carousel_image2.jpg', class: 'd-block w-100' %>
        <div class="carousel-caption">
          <h3>Enjoy free events, all year long!</h3>
          <h6 class="d-none d-md-block">Learn more about our free concerts in public places</h6>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'application/carousel_image3.jpg', class: 'd-block w-100' %>
        <div class="carousel-caption">
          <h3>GET INVOLVED!</h3>
          <h6 class="d-none d-md-block">Become a volunteer, register as a vendor and get ready for this year's artwork contest!</h6>
        </div>
      </div>
    </div>
  </div>
</div>

<hr class="row" />

<div class="row">
  <div class="col-sm-12 col-md-4">
    <%= button_to 'BUY TICKETS', tickets_path, class: "btn main-button", :method => :get %>
  </div>
  <div class="col-sm-12 col-md-4">
    <%= button_to 'CONTESTANT REGISTRATION', contestants_path, class: "btn main-button", :method => :get %>
  </div>
  <div class="col-sm-12 col-md-4">
    <%= button_to 'GET INVOLVED', getinvolved_path, class: "btn main-button", :method => :get %>
  </div>
</div>

<div class="row">
  <div class="card border-dark">
    <div class="card-header bg-transparent">
      <h3>2017 Artwork Contest</h3>
    </div>
    <div class="card-body">
      <h4 class="card-subtitle">The 2017 winner is...</h4>
      <img class="card-image" src="http://topangabanjofiddle.org/images/2017/2017_graphic_winner.jpg">
      <p class="card-text">Cheryl Pelly!<br><br>
        Thanks to all who submitted. Graphic submission rules will be revised for 2018, and we hope to hear from you all again!
      </p>
    </div>
    <div class="card-footer">
      <p class="float-right">Posted October 9th, 2017 by Juli E.</p>
    </div>
  </div>
</div>

app/views/concerts/index.html.erb
<h1>Concerts#index</h1>
<p>Find me in app/views/concerts/index.html.erb</p>

app/views/contestants/register.html.erb
<h1>New User</h1>

<%= render 'users/form', user: @user %>

<%= link_to 'Back', contestants_path %>

app/views/event/index.html.erb
<h1>Event#index</h1>
<p>Find me in app/views/event/index.html.erb</p>

app/views/get_involved/index.html.erb
<h1>GetInvolved#index</h1>
<p>Find me in app/views/get_involved/index.html.erb</p>

app/views/tickets/index.html.erb
<h1>Tickets#index</h1>
<p>Find me in app/views/tickets/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :user_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :user_city %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :user_zip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Type</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.zip %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user.zip %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/vendors/index.html.erb
<h1>Vendors#index</h1>
<p>Find me in app/views/vendors/index.html.erb</p>