config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'concerts/', to: 'concerts#index', as: 'concerts'

  get 'tickets/', to: 'tickets#index', as: 'tickets'

  get 'vendors/', to: 'vendors#index', as: 'vendors'

  get 'contestants/', to: 'contestants#index', as: 'contestants'
  get 'contestants/register', to: 'contestants#register', as: 'registration'
  post 'contestants/register', to: 'users#create'

  get 'about/', to: 'about#index', as: 'about'

  get 'event/', to: 'event#index', as: 'event'

  get 'get_involved/', to: 'get_involved#index', as: 'getinvolved'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
  end
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  def index
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :user_type, :address, :city, :zip)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/get_involved_helper.rb
module GetInvolvedHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TBFC - Topanga Banjo Fiddle Contest</title>
    <%= csrf_meta_tags %>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container-fluid'>
      <header class='row no-gutters'>
        <div class='col-sm-2 d-none d-sm-block'>
          <%= image_tag 'shared/logo.jpg', class: 'img-fluid' %>
        </div>
        <div class='col-xs-12 col-sm-10'>
          <%= image_tag 'shared/header.jpg', class: 'img-fluid header' %>
        </div>
      </header>
      <div class='row'>
        <div class='col-12 col-md-2 nav-fix'>
          <nav class='navbar navbar-expand-md'>
            <button class='navbar-toggler expand-button' type='button' data-toggle='collapse' data-target="#navbarExpanded">
              TAKE ME TO...
            </button>
            <div class="collapse navbar-collapse flex-column" id="navbarExpanded">
              <%= button_to 'HOME', root_path, class: 'btn btn-outline-dark btn-block', :method => :get %>
              <%= button_to 'EVENT INFO', event_path, class: 'btn btn-outline-dark btn-block', :method => :get %>
              <%= button_to 'FREE CONCERTS', concerts_path, class: 'btn btn-outline-dark btn-block', :method => :get %>
              <%= button_to 'TICKETS', tickets_path, class: 'btn btn-outline-dark btn-block', :method => :get %>
              <%= button_to 'CONTESTANTS', contestants_path, class: 'btn btn-outline-dark btn-block', :method => :get %>
              <%= button_to 'ABOUT', about_path, class: 'btn btn-outline-dark btn-block', :method => :get %>
            </div>
          </nav>
        </div>
        <div class='page-content col-12 col-md-10'>
          <%= yield %>
        </div>
      </div>
  </body>
</html>